// Copyright (c) 2026 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerinax/openrouter;

const DEFAULT_OPENROUTER_SERVICE_URL = "https://openrouter.ai/api/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;

# ModelProvider is a client class that provides an interface for interacting with
# LLMs via the OpenRouter unified API, which supports models from OpenAI, Anthropic,
# Google, Meta, Mistral, and many other providers.
@display {
    label: "OpenRouter Model Provider"
}
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    private final openrouter:Client openrouterClient;
    private final http:Client streamClient;
    private final string modelType;
    private final decimal? temperature;
    private final int maxTokens;
    private final openrouter:SendChatCompletionRequestHeaders & readonly requestHeaders;

    # Initializes the OpenRouter model provider with the given configuration.
    #
    # + apiKey - The OpenRouter API key (obtain from https://openrouter.ai/keys)
    # + modelType - The OpenRouter model to use (e.g., `openai/gpt-4o`, `anthropic/claude-3.5-sonnet`)
    # + serviceUrl - The base URL of the OpenRouter API endpoint
    # + siteUrl - Optional site URL sent as `HTTP-Referer` header for OpenRouter attribution
    # + siteName - Optional site name sent as `X-OpenRouter-Title` header for OpenRouter attribution
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} string modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_OPENROUTER_SERVICE_URL,
            @display {label: "Site URL"} string? siteUrl = (),
            @display {label: "Site Name"} string? siteName = (),
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        openrouter:Client|ai:Error openrouterClient = buildOpenRouterClient(apiKey, serviceUrl, connectionConfig);
        if openrouterClient is ai:Error {
            return openrouterClient;
        }
        http:Client|error streamClient = new (serviceUrl, {
            auth: {
                token: apiKey
            },
            httpVersion: connectionConfig.httpVersion,
            timeout: connectionConfig.timeout
        });
        if streamClient is error {
            return error ai:Error("Failed to initialize the OpenRouter streaming client", streamClient);
        }
        self.openrouterClient = openrouterClient;
        self.streamClient = streamClient;
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;

        // Build optional OpenRouter attribution headers
        openrouter:SendChatCompletionRequestHeaders headers = {};
        if siteUrl is string {
            headers["HTTP-Referer"] = siteUrl;
        }
        if siteName is string {
            headers["X-OpenRouter-Title"] = siteName;
        }
        self.requestHeaders = headers.cloneReadOnly();
    }

    # Sends a chat request to the OpenRouter model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openrouter");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temperature = self.temperature;
        if temperature is decimal {
            span.addTemperature(temperature);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        openrouter:ChatGenerationParams request = {
            max_completion_tokens: <decimal>self.maxTokens,
            stop,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools)
        };
        if temperature is decimal {
            request.temperature = temperature;
        }
        if tools.length() > 0 {
            request.tools = tools.map(t => <openrouter:ToolDefinitionJson>{
                'type: "function",
                'function: {name: t.name, description: t.description, parameters: t.parameters}
            });
            span.addTools(tools);
        }

        openrouter:ChatResponse|error response = self.openrouterClient->/chat/completions.post(
            request, self.requestHeaders);
        if response is error {
            ai:Error err = buildHttpError(response);
            span.close(err);
            return err;
        }

        openrouter:ChatResponseChoice[] choices = response.choices;
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        decimal? inputTokens = response?.usage?.prompt_tokens;
        if inputTokens is decimal {
            span.addInputTokenCount(<int>inputTokens);
        }
        decimal? outputTokens = response?.usage?.completion_tokens;
        if outputTokens is decimal {
            span.addOutputTokenCount(<int>outputTokens);
        }
        anydata finishReasonRaw = choices[0].finish_reason;
        string? finishReason = finishReasonRaw is string ? finishReasonRaw : ();
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage|ai:Error message = self.convertResponseToAssistantMessage(choices[0].message);
        if message is ai:Error {
            span.close(message);
            return message;
        }
        if tools.length() > 0 && message.toolCalls is () {
            string finishInfo = finishReason is string ? string ` (finish_reason: '${finishReason}')` : "";
            ai:Error err = error ai:LlmInvalidResponseError(
                string `Model '${self.modelType}' did not return a tool call despite ${tools.length()} ` +
                string `tool(s) being provided${finishInfo}. The model may not support function calling, ` +
                "or it chose to respond with plain text. Try a model that supports tool use, or adjust the prompt."
            );
            span.close(err);
            return err;
        }
        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value of the type specified by
    # the `td` type descriptor. For complex record types, annotate the type with
    # `@ai:JsonSchema` to enable compile-time schema generation.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt,
            @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openrouter.Generator"
    } external;

    # Sends a streaming chat request to the OpenRouter model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of chat completion chunks, or an error in case of failures
    remote function chatStream(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ai:ChatCompletionChunk, ai:Error?>|ai:Error {
        openrouter:ChatGenerationParams request = {
            max_completion_tokens: <decimal>self.maxTokens,
            stop,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools),
            // OpenRouter always includes full usage details on the final chunk,
            // so `stream_options.include_usage` is unnecessary (and deprecated).
            'stream: true
        };
        decimal? temperature = self.temperature;
        if temperature is decimal {
            request.temperature = temperature;
        }
        if tools.length() > 0 {
            request.tools = tools.map(t => <openrouter:ToolDefinitionJson>{
                'type: "function",
                'function: {name: t.name, description: t.description, parameters: t.parameters}
            });
        }

        // The OpenRouter connector deserializes the full response, so streaming
        // uses the raw `streamClient`; copy through the attribution headers.
        map<string|string[]> headers = {};
        foreach [string, anydata & readonly] [key, value] in self.requestHeaders.entries() {
            if value is string {
                headers[key] = value;
            }
        }

        http:Response|error response = self.streamClient->post("/chat/completions", request, headers);
        if response is error {
            return error ai:LlmConnectionError("Error while connecting to the model for streaming", response);
        }
        stream<http:SseEvent, error?>|error sseStream = response.getSseEventStream();
        if sseStream is error {
            return error ai:Error("Failed to open the SSE stream from the model", sseStream);
        }
        // Assigning to an explicitly typed local first; `new (...)` cannot infer
        // the stream type when the function returns a union (`stream<...>|Error`).
        stream<ai:ChatCompletionChunk, ai:Error?> chunkStream = new (new OpenRouterChunkIterator(sseStream));
        return chunkStream;
    }

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer. Only `string` is supported as the expected type.
    #
    # + prompt - The prompt to use in the chat request
    # + td - The expected type of the streamed value; must be `string`
    # + return - A stream of the generated value, or an error if the type is unsupported
    remote function generateStream(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
            returns stream<td, ai:Error?>|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openrouter.StreamGenerator"
    } external;

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns openrouter:Message[]|ai:Error {
        openrouter:Message[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            openrouter:UserMessage userMsg = {role: "user", content: check getChatMessageStringContent(messages.content)};
            chatCompletionRequestMessages.push(userMsg);
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatAssistantMessage {
                chatCompletionRequestMessages.push(self.buildRequestAssistantMessage(message));
            } else if message is ai:ChatUserMessage {
                openrouter:UserMessage userMsg = {role: "user", content: check getChatMessageStringContent(message.content)};
                chatCompletionRequestMessages.push(userMsg);
            } else if message is ai:ChatSystemMessage {
                openrouter:SystemMessage sysMsg = {role: "system", content: check getChatMessageStringContent(message.content)};
                chatCompletionRequestMessages.push(sysMsg);
            } else if message is ai:ChatFunctionMessage {
                // Map legacy function message to tool response; use name as tool_call_id
                openrouter:ToolResponseMessage toolMsg = {
                    role: "tool",
                    content: message.content ?: "",
                    tool_call_id: message.name
                };
                chatCompletionRequestMessages.push(toolMsg);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function buildRequestAssistantMessage(ai:ChatAssistantMessage message)
    returns openrouter:AssistantMessage {
        openrouter:AssistantMessage assistantMessage = {role: "assistant"};
        ai:FunctionCall[]? toolCalls = message.toolCalls;
        if toolCalls is ai:FunctionCall[] && toolCalls.length() > 0 {
            ai:FunctionCall functionCall = toolCalls[0];
            assistantMessage.tool_calls = [
                {
                    id: "call_" + functionCall.name,
                    'type: "function",
                    'function: {
                        name: functionCall.name,
                        arguments: functionCall.arguments.toJsonString()
                    }
                }
            ];
        }
        string? content = message?.content;
        if content is string {
            assistantMessage.content = content;
        }
        return assistantMessage;
    }

    private isolated function convertResponseToAssistantMessage(openrouter:AssistantMessage message)
    returns ai:ChatAssistantMessage|ai:LlmError {
        do {
            ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
            anydata? rawContent = message?.content;
            if rawContent is string {
                chatAssistantMessage.content = rawContent;
            }
            openrouter:ChatMessageToolCall[]? toolCalls = message?.tool_calls;
            if toolCalls is openrouter:ChatMessageToolCall[] && toolCalls.length() > 0 {
                // Modern tool_calls path
                ai:FunctionCall[] functionCalls = [];
                foreach openrouter:ChatMessageToolCall toolCall in toolCalls {
                    json arguments = check toolCall.'function.arguments.fromJsonString();
                    functionCalls.push({
                        name: toolCall.'function.name,
                        arguments: check arguments.cloneWithType()
                    });
                }
                chatAssistantMessage.toolCalls = functionCalls;
            } else {
                // Legacy function_call path — AssistantMessage is an open record so the
                // field is still present even though it is not declared on the type.
                map<json>|error legacyCall = message["function_call"].cloneWithType();
                if legacyCall is map<json> {
                    string name = check legacyCall["name"].ensureType();
                    string argsStr = check legacyCall["arguments"].ensureType();
                    json arguments = check argsStr.fromJsonString();
                    chatAssistantMessage.toolCalls = [{
                        name,
                        arguments: check arguments.cloneWithType()
                    }];
                }
            }
            return chatAssistantMessage;
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }
}

# Iterator that converts OpenRouter's Server-Sent Event stream into a stream of
# normalized `ai:ChatCompletionChunk` values. Each `data:` line is parsed into the
# OpenRouter wire chunk and mapped via `toAiChunk`; the terminating `[DONE]` sentinel,
# blank lines, and unparseable keep-alive comments are skipped.
class OpenRouterChunkIterator {
    private stream<http:SseEvent, error?> sseStream;

    isolated function init(stream<http:SseEvent, error?> sseStream) {
        self.sseStream = sseStream;
    }

    public isolated function next() returns record {|ai:ChatCompletionChunk value;|}|ai:Error? {
        while true {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                return ();
            }
            if event is error {
                return error ai:Error("Error while reading the model stream", event);
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == "[DONE]" {
                return ();
            }
            json|error payload = trimmedData.fromJsonString();
            if payload is error {
                continue;
            }
            CreateChatCompletionStreamResponse|error wireChunk = payload.cloneWithType();
            if wireChunk is error {
                continue;
            }
            return {value: toAiChunk(wireChunk)};
        }
    }

    public isolated function close() returns ai:Error? {
        error? result = self.sseStream.close();
        if result is error {
            return error ai:Error("Error while closing the model stream", result);
        }
        return ();
    }
}

# Builds the string stream behind the dependently-typed `generateStream`. The
# native `StreamGenerator` shim trampolines here so the type gating stays in
# Ballerina. Only `string` is supported; other types yield an error because a
# partial generation is a valid value only for `string`. When valid, the
# underlying `chatStream` chunks are projected onto their text fragments.
#
# + llmModel - The model provider whose `chatStream` supplies the chunks
# + prompt - The prompt to send to the model
# + td - The caller's expected type; must be `string`
# + return - A stream of text fragments, or an error if the type is unsupported
function generateLlmResponseStream(ModelProvider llmModel, ai:Prompt prompt, typedesc<anydata> td)
        returns stream<string, ai:Error?>|ai:Error {
    if td !is typedesc<string> {
        return error ai:Error("This data type is not supported for streaming. " +
            "'generateStream' supports only 'string'; use 'generate' for structured types.");
    }
    stream<ai:ChatCompletionChunk, ai:Error?> chunks = check llmModel->chatStream({role: ai:USER, content: prompt});
    stream<string, ai:Error?> textStream = new (new ChunkTextIterator(chunks));
    return textStream;
}

# Projects a normalized `ai:ChatCompletionChunk` stream onto its text content,
# yielding each non-empty `delta.content` fragment and skipping tool-call and
# usage-only chunks. Backs `generateLlmResponseStream`.
class ChunkTextIterator {
    private stream<ai:ChatCompletionChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatCompletionChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatCompletionChunk value;|}|ai:Error? next = self.chunks.next();
            if next is () {
                return ();
            }
            if next is ai:Error {
                return next;
            }
            ai:ChatCompletionChunkChoice[] choices = next.value.choices;
            if choices.length() == 0 {
                continue;
            }
            string? content = choices[0].delta.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        error? result = self.chunks.close();
        if result is error {
            return error ai:Error("Error while closing the model stream", result);
        }
        return ();
    }
}
